project_id = "qjeuvqmvvjuvingoipjd"

[functions.ban-user]
verify_jwt = false

[functions.admin-manage-role]
verify_jwt = false

[functions.create-game-sale]
verify_jwt = false

[functions.complete-transaction]
verify_jwt = false

[functions.moderate-forum-content]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.send-payment-request]
verify_jwt = false

[functions.pay-payment-request]
verify_jwt = false

[functions.create-seller-account]
verify_jwt = false

[functions.check-seller-status]
verify_jwt = false
